services:
    mongodb:
        image: mongo:7.0
        container_name: chatbot_mongodb
        restart: unless-stopped
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: chatbot_db
        volumes:
            - mongodb_data:/data/db
        networks:
            - chatbot_network

    qdrant:
        image: qdrant/qdrant:v1.7.4
        container_name: chatbot_qdrant
        restart: unless-stopped
        ports:
            - "6333:6333"
            - "6334:6334"
        volumes:
            - qdrant_data:/qdrant/storage
        networks:
            - chatbot_network

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: chatbot_backend
        restart: unless-stopped
        ports:
            - "3000:3000"
        env_file:
            - ./backend/.env
        depends_on:
            - mongodb
            - qdrant
        networks:
            - chatbot_network

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: chatbot_frontend
        restart: unless-stopped
        ports:
            - "5173:5173"
        networks:
            - chatbot_network

volumes:
    mongodb_data:
    qdrant_data:

networks:
    chatbot_network:
        driver: bridge
