services:
    # MongoDB Database
    mongodb:
        image: mongo:7.0
        container_name: chatbot_mongodb
        restart: unless-stopped
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: chatbot_db
        volumes:
            - mongodb_data:/data/db
            - ./backend/scripts/seed.js:/docker-entrypoint-initdb.d/seed.js:ro
        networks:
            - chatbot_network

    # Qdrant Vector Database
    qdrant:
        image: qdrant/qdrant:v1.7.4
        container_name: chatbot_qdrant
        restart: unless-stopped
        ports:
            - "6333:6333"
            - "6334:6334"
        volumes:
            - qdrant_data:/qdrant/storage
        networks:
            - chatbot_network

    # Backend Service (Node.js + Python)
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: chatbot_backend
        restart: unless-stopped
        ports:
            - "3000:3000"
        env_file:
            - ./backend/.env
        environment:
            NODE_ENV: production
            PORT: 3000
            MONGODB_URI: mongodb://admin:password@mongodb:27017/chatbot_db?authSource=admin
            QDRANT_URL: http://qdrant:6333
            QDRANT_COLLECTION_NAME: chatbot_documents
        depends_on:
            - mongodb
            - qdrant
        volumes:
            - ./backend:/app
            - /app/node_modules
        networks:
            - chatbot_network
        command: npm start

    # Frontend Service (React)
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: chatbot_frontend
        restart: unless-stopped
        ports:
            - "5173:5173"
        depends_on:
            - backend
        networks:
            - chatbot_network

volumes:
    mongodb_data:
    qdrant_data:

networks:
    chatbot_network:
        driver: bridge
